[pytest]
env_files =
    .test.env
env_override_existing_values = 1

testpaths = tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*

pythonpath = .

addopts = -q --disable-warnings --maxfail=1 --tb=short

log_cli = true
log_cli_level = INFO

markers =
    slow: slow tests
    unit: unit tests
    integration: integration tests
    e2e: end-to-end tests