"""add indexes

Revision ID: 84d39e1bd76e
Revises: a4144faa4c9e
Create Date: 2026-04-17 21:08:27.164530

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '84d39e1bd76e'
down_revision: Union[str, Sequence[str], None] = 'a4144faa4c9e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('wallet_id_index', 'balances', ['wallet_id'], unique=False)
    op.create_index('owner_id_index', 'wallets', ['owner_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('owner_id_index', table_name='wallets')
    op.drop_index('wallet_id_index', table_name='balances')
    # ### end Alembic commands ###
